In [ ]:
'20241'

'20241'

In [ ]:
"20241"[-1]

'1'

In [ ]:
x = [0,]*n;
x.append(5)
x

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]

# **Vectores con numpy**

In [ ]:
import numpy as np

In [ ]:
n = int(input("Ingrese la cantidad de elementos presentes en el vector: "))
n

Ingrese la cantidad de elementos presentes en el vector: 10


10

#### **Función range para generar secuencia numérica**

In [ ]:
for i in range(1,n+1,2):
  print(i, end="|")

1|3|5|7|9|

### **Lectura de un vector**

In [ ]:
v = np.zeros((n+1,))

for i in range(1,n+1):
  # print(i)
  v[i] = int(input(f'Ingrese el elemento v[{i}]: '))


Ingrese el elemento v[1]: 0
Ingrese el elemento v[2]: 0
Ingrese el elemento v[3]: 0
Ingrese el elemento v[4]: 0
Ingrese el elemento v[5]: 0
Ingrese el elemento v[6]: 0
Ingrese el elemento v[7]: 1
Ingrese el elemento v[8]: 5
Ingrese el elemento v[9]: 6
Ingrese el elemento v[10]: 1
0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 1.0 | 5.0 | 6.0 | 1.0 | 

In [ ]:
for i in range(1,n+1):
  print(v[i], end=" | ")

# **Matrices con numpy**

In [ ]:
n = 3
A = np.zeros((n+1,n+1))
B = np.zeros((n+1,n+1))
for i in range(1,n+1):
  for j in range(1, n+1):
    A[i][j] = int(input(f'Ingrese el elemento A{i,j}: '))
    B[i][j] = int(input(f'Ingrese el elemento B{i,j}: '))
    # print(A[i][j], end="|")
  # print("")

Ingrese el elemento A(1, 1): 1
Ingrese el elemento B(1, 1): 2
Ingrese el elemento A(1, 2): 3
Ingrese el elemento B(1, 2): 4
Ingrese el elemento A(1, 3): 5
Ingrese el elemento B(1, 3): 6
Ingrese el elemento A(2, 1): 7
Ingrese el elemento B(2, 1): 8
Ingrese el elemento A(2, 2): 9
Ingrese el elemento B(2, 2): 10
Ingrese el elemento A(2, 3): 11
Ingrese el elemento B(2, 3): 12
Ingrese el elemento A(3, 1): 13
Ingrese el elemento B(3, 1): 14
Ingrese el elemento A(3, 2): 15
Ingrese el elemento B(3, 2): 16
Ingrese el elemento A(3, 3): 17
Ingrese el elemento B(3, 3): 18


## **Imprimir matriz**

In [ ]:

for i in range(1,n+1):
  for j in range(1, n+1):
    print(A[i][j], end="|")
  print("")

1.0|3.0|5.0|
7.0|9.0|11.0|
13.0|15.0|17.0|


In [ ]:
print(A[1:,1:])

[[ 1.  3.  5.]
 [ 7.  9. 11.]
 [13. 15. 17.]]


### **Producto matricial**

In [ ]:
C = np.zeros((n+1,n+1))
for i in range(1,n+1):
  for j in range(1, n+1):
    sum = 0;
    for k in range(1, n+1):
      sum += A[i][k]*B[k][j] #sum = sum + A[i][k]*B[k][j]
    C[i][j] = sum
print(C[1:,1:])

[[ 96. 114. 132.]
 [240. 294. 348.]
 [384. 474. 564.]]


  Note que numpy es una librería para operaciones numéricas entre arreglos con 1, 2, o más dimensiones. Una forma sencilla de operar dos matrices es como sigue

In [ ]:
(A@B)[1:, 1:]

array([[ 96., 114., 132.],
       [240., 294., 348.],
       [384., 474., 564.]])

# **Sin embargo para efectos del curso es indispensable conocer y desarrollar la lógica asociada a los algoritmos. Es decir, no se permite usar las funciones predefinidas por la librería de numpy.**

In [ ]:
A.T[1:,1:]

array([[ 1.,  7., 13.],
       [ 3.,  9., 15.],
       [ 5., 11., 17.]])

**Ascii de una caracter**

In [ ]:
ord("ajuanlava"[0])

97